# Generated by Django 5.2 on 2025-06-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoRescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=200)),
                ('foto_equipo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteRescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('pdf_informe', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.equiporescate')),
            ],
        ),
        migrations.CreateModel(
            name='Rescate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('ubicación', models.CharField(max_length=200)),
                ('foto_rescate', models.ImageField(blank=True, null=True, upload_to='rescates/')),
                ('equipos', models.ManyToManyField(through='Animales.ReporteRescate', to='Animales.equiporescate')),
            ],
        ),
        migrations.AddField(
            model_name='reporterescate',
            name='rescate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Animales.rescate'),
        ),
    ]
