# Generated by Django 5.2 on 2025-06-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescate',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='rescate',
            name='ubicación',
        ),
        migrations.AddField(
            model_name='rescate',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='equiporescate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='rescate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.rescate'),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
