# Generated by Django 5.2 on 2025-06-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0002_remove_rescate_equipos_remove_rescate_ubicación_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rescate',
            name='equipos',
            field=models.ManyToManyField(related_name='rescates', to='Animales.equiporescate'),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Animales.equiporescate'),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='rescate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Animales.rescate'),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='rescate',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Animales.especie'),
        ),
    ]
