# Generated by Django 5.2 on 2025-06-12 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0003_especie_rescate_equipos_alter_reporterescate_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescate',
            name='equipos',
        ),
        migrations.AlterField(
            model_name='equiporescate',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equiporescate',
            name='foto_equipo',
            field=models.ImageField(default='equipos/default.jpg', upload_to='equipos/'),
        ),
        migrations.AlterField(
            model_name='equiporescate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Animales.equiporescate'),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporterescate',
            name='pdf_informe',
            field=models.FileField(default='reportes/default.pdf', upload_to='reportes/'),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Animales.especie'),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rescate',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
    ]
