# Generated by Django 5.2 on 2025-06-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0004_remove_rescate_equipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
