# Generated by Django 5.0.6 on 2025-06-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0005_especie_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiporescate',
            name='fecha_actualizacion',
            field=models.DateField(default='2024-06-01'),
        ),
        migrations.AddField(
            model_name='equiporescate',
            name='fecha_creacion',
            field=models.DateField(default='2024-06-01'),
        ),
    ]
