# Generated by Django 5.0.6 on 2025-06-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0006_equiporescate_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiporescate',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equiporescate',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
